using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace codefirst
{
    //steps:
    //step-1:create console project
    //step-2 rightclick on project -> add new item->ado.net entity model->emptycode first >click finish
    //step-3: create class ipl.cs
    //step-4 change model1.cs
    //step-5:create cruddemo.cs
    //step-6:change app.config connectinstring including database name ,server name.
    //then the table will be ganerated and the database is also autogenerated

    internal class curddemo
    {
        Model1 dc = new Model1();
        //public void Display()
        //{
        //    var res = from t in dc.Ipls select t;
        //    foreach (var item in res)
        //    {
        //        Console.WriteLine(item.TeamId+":"+item.TeamName+":"+item.State+":"+item.Captain);
        //    }
        //}
        ////tables will be generated automaticaly when u call any method having savechanges
        //public void insert()
        //{
        //    ipl ob = new ipl() { TeamId = 1, TeamName = "RCB", Captain = "virat", State = "karnataka" };
        //    dc.Ipls.Add(ob);
        //    int i = dc.SaveChanges();
        //    Console.WriteLine("rows inserted"+i);
        //}
        public void insertnewstudents()
        {
            try
            {


                student s = new student()
                {
                    studentId = 100,
                    Studentname = "Raj",  // invalid
                    DOB = DateTime.Now,
                    Class = 10, // invalid
                    Email = "raj@gmail.com"// invalid
                };

                dc.Students.Add(s);
                int res = dc.SaveChanges();
                Console.WriteLine("total record inserted is " + res);
            }
            catch (Exception ex)
            {

                var res = dc.GetValidationErrors();

                foreach (var item in res)
                {
                    if (item.ValidationErrors.Count > 0)
                    {
                        foreach (var err in item.ValidationErrors)
                        {
                            Console.WriteLine(err.ErrorMessage);
                        }

                    }
                }

            }
        }
    }
}
