//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Databasefirstass
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Employee
    {
      
        public string EmpId { get; set; }
        public string EmpName { get; set; }
        public string DepartmentName { get; set; }
        public Nullable<int> Salary { get; set; }
        public Nullable<int> YearOfJoining { get; set; }
    }
}
