--1. Write a query to display the custid ,name, age, orderid,orderdate for 
--product laptop or mobile, sort data by name in descending order

select c.custid,c.custname,c.age,o.orderid,o.orderdate
from customers c join orders o on c.custid =o.custid
where o.product in ('Laptop','Mobile') order by c.custname desc;

--2)Write a SQL statement to find the list of customers who live in the 
--same city as surya, and display custid , custname , price (price > 500)

select c.custid,c.custname,o.price from customers c
join orders o on c.custid=o.custid where caddress=(select
caddress from customers where custname='surya')
and o.price>500;

--3) Write a query to find the name of customers along with order details 
--who purchased more than two products

select c.custid,c.custname,o.orderid,o.product,o.qty,o.price from 
customers c join orders o on c.custid=o.custid
where o.qty>2

--4)A discount of 20% has been announced to all customers who resides 
--in Bangalore . display custid , custname , orderid and discount price

select c.custid,c.custname,o.orderid,o.price as original_price ,
o.price*0.80 as discounted_price from customers c 
join orders o on c.custid=o.custid
where c.caddress='Bangalore';

--5). write a query to join three tables (create products table for the same)


create table products (productid int primary key,
product varchar(50));
insert into products values(1,'Laptop'),
(2,'Mobile'),
(3,'Charger'),
(4,'Keyboard');
select c.custid,c.custname,o.orderid,o.orderdate,p.productid,
p.product,o.price,o.qty from customers c
join orders o on c.custid=o.custid
join products p on o.product=p.product;

--6)6. update price by 5% from orders table for customers who resides in 
--vizag and bangalore

update o 
set o.price=o.price*1.05
from orders o join customers c on c.custid=o.custid
where c.caddress in ('Vizag','Bangalore');

--7)create a report in following format

--1. Custname should be uppercase
--2. Display only first 3 character of product
--3. The report should be of December 200

select 'cid:'+cast(c.custid as varchar) +'-ordid:'+
cast(o.orderid as varchar) as custidord,
upper(c.custname) as custname,
left(o.product,3) as product,o.price,o.orderdate
from customers c join orders o on c.custid=o.custid
where month(o.orderdate)=12 and year(o.orderdate)=2000;


--validations
--1)Create Table Students
--StudentRollNumber
--StudentName
--DOB
--Class
--I. Student Roll Number should be autogenerated as (100,200,300 ).
--Alter Command
--a. DOB cannot be greater then current date
--b. Class should be between 1 - 10

create table student(studentRollNumber int identity(100,100) primary key,
studentname varchar(50),dob date,class int);
alter table student add constraint check_dob check (dob<=getdate());
alter table student add constraint class_check check (class between 1 and 10);

--3)Create Table purchase
--Productid
--PurchaseDate
--Serialno
--Price
--Qty 
--Total
--  The default value for purchase date should be the system date.
--  Serialno should be a unique 
--  Total to be autogenerated
--  Create a rule qty should be greater than 1
--  Create a rule where price should be between 1000 and 700
create table purchase (
productid int,purchasedate date default getdate(),
serialno int unique,
price int,
qty int,
total as (price*qty));
GO
create rule qty_rule as @qty>1;
GO
exec sp_bindrule 'qty_rule','purchase.qty';
insert into purchase (productid,serialno,price,qty) values(102,4,200,1);

GO
create rule price_rule as @price between 700 and 1000;
GO
exec sp_bindrule 'price_rule','purchase.price';
insert into purchase (productid,serialno,price,qty) values(103,3,700,4);

--2)Create Table Stock
--StockId
--MinStockLvl
--MaxStockLvl
--Alter Command
--The MaxStockLvl should be Greater than MinStockLvl.
--Stock id should be following format
--stc-11-aaa
--Start with 3 alphabets following by   followed by 2 digit followed by   and 
--ending with 3 alphabets .

create table stock(
stockid varchar(10) primary key,
minstocklvl int,maxstocklvl int);
alter table stock add constraint check_min
check (maxstocklvl > minstocklvl);
alter table stock add constraint check_id
check (stockid like '[A-Z][A-Z][A-z]-[0-9][0-9]-[A-Z][A-Z][A-Z]');
insert into stock (stockid, minstocklvl, maxstocklvl)
values ('STC-11-AAA', 10, 20);
insert into stock (stockid, minstocklvl, maxstocklvl)
values ('schs2232kn', 10, 20);


